### ISSUE TITLE
DSP

### ISSUE THREAD

**Issue by arjunmenon** [Arve/brutepi#1]
Hey
In addition to BruteFIR, can it work with a DSP setup - https://github.com/bmc0/dsp/wiki/System-Wide-DSP-Guide

**Comment by Arve** [comment]
@arjunmenon This will not work with the guide you linked - this is merely a shorthand for installing, configuring and optimizing convolution-based correction using BruteFIR, and pretty much presupposes that you generate the corrections from within a package like Room EQ Wizard, FIR Designer, RePhase or Accourate.    This package specifically avoids using PulseAudio, and so is incompatible with the approach chosen in that document

If you wish to use this script to apply speaker corrections from for instance noaudiophile.com, you will have to enter the corrections manually in the EQ window in Room EQ Wizard, and then use "Export Filter Impulse Response" from within REW.
